# Generated by Django 5.2.14 on 2026-05-10 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('reforestation', 'Reforestation'), ('soil_carbon', 'Soil Carbon'), ('renewable_energy', 'Renewable Energy'), ('methane_capture', 'Methane Capture'), ('blue_carbon', 'Blue Carbon'), ('direct_air_capture', 'Direct Air Capture')], max_length=30)),
                ('location_text', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('standard', models.CharField(choices=[('verra', 'Verra VCS'), ('gold_standard', 'Gold Standard'), ('acr', 'ACR'), ('car', 'CAR'), ('puro', 'Puro.earth')], max_length=30)),
                ('total_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_sequestered_tco2e', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carbon_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.PositiveIntegerField()),
                ('price_per_credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold Out'), ('expired', 'Expired')], default='active', max_length=10)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='marketplace.carbonproject')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_listings',
                'ordering': ['-listed_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.creditlisting')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
