"""
C0 Model Training Script
=========================
Reads the cleaned India-specific training dataset (generated by prepare_data.py)
and trains a Random Forest model for carbon credit estimation.

Usage:
    1. Run prepare_data.py first to generate the training dataset
    2. Then run this script to train and save the model

    python prepare_data.py   # Step 1: Clean & combine datasets
    python train.py          # Step 2: Train model
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error
import joblib
import os

DATA_DIR = 'data'
MODEL_DIR = 'models'
os.makedirs(MODEL_DIR, exist_ok=True)

print("=" * 70)
print("  C0 CARBON CREDIT ESTIMATOR — Model Training")
print("=" * 70)

# ──────────────────────────────────────────────────────────────────────────────
# 1. Load the cleaned training dataset
# ──────────────────────────────────────────────────────────────────────────────
train_path = os.path.join(DATA_DIR, 'india_training_dataset.csv')

if not os.path.exists(train_path):
    print(f"\n❌ Training dataset not found at '{train_path}'")
    print("   Please run 'python prepare_data.py' first to generate it.")
    exit(1)

print(f"\n📦 Loading training dataset: {train_path}")
df = pd.read_csv(train_path)
print(f"   {len(df):,} samples × {len(df.columns)} features")
print(f"   Activity types: {', '.join(sorted(df['activity_type'].unique()))}")
print(f"   States: {df['state'].nunique()}")
print(f"   Climate zones: {', '.join(sorted(df['climate_zone'].unique()))}")

# ──────────────────────────────────────────────────────────────────────────────
# 2. Also load the macro India data for context logging
# ──────────────────────────────────────────────────────────────────────────────
macro_path = os.path.join(DATA_DIR, 'india_combined_clean.csv')
if os.path.exists(macro_path):
    macro_df = pd.read_csv(macro_path)
    latest = macro_df.iloc[-1]
    print(f"\n📊 India macro context (year {int(latest['year'])}):")
    if 'co2' in latest and not pd.isna(latest['co2']):
        print(f"   Total CO2: {latest['co2']:.2f} Mt")
    if 'land_use_change_co2' in latest and not pd.isna(latest['land_use_change_co2']):
        print(f"   Land-use change CO2: {latest['land_use_change_co2']:.2f} Mt")
    if 'total_ghg' in latest and not pd.isna(latest['total_ghg']):
        print(f"   Total GHG: {latest['total_ghg']:.2f} Mt CO2eq")

# ──────────────────────────────────────────────────────────────────────────────
# 3. Feature / Target Split
# ──────────────────────────────────────────────────────────────────────────────
print("\n⚙️ Preparing features and target...")

features = [
    'land_size_hectares',
    'activity_type',
    'climate_zone',
    'state',
    'project_age_years',
    'avg_rainfall_mm',
    'forest_cover_pct',
    'soil_organic_carbon',
]
target = 'estimated_carbon_credits_tco2e'

# Validate columns exist
missing = [f for f in features + [target] if f not in df.columns]
if missing:
    print(f"❌ Missing columns: {missing}")
    exit(1)

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"   Train: {len(X_train):,} samples")
print(f"   Test:  {len(X_test):,} samples")

# ──────────────────────────────────────────────────────────────────────────────
# 4. Build the ML Pipeline
# ──────────────────────────────────────────────────────────────────────────────
print("\n🔧 Building pipeline...")

categorical_features = ['activity_type', 'climate_zone', 'state', 'soil_organic_carbon']
numerical_features = ['land_size_hectares', 'project_age_years', 'avg_rainfall_mm', 'forest_cover_pct']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False),
         categorical_features)
    ],
    remainder='passthrough'  # numerical features pass through as-is
)

model_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(
        n_estimators=200,
        max_depth=25,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    ))
])

# ──────────────────────────────────────────────────────────────────────────────
# 5. Train
# ──────────────────────────────────────────────────────────────────────────────
print("\n🏋️ Training Random Forest model (200 estimators)...")
model_pipeline.fit(X_train, y_train)

# ──────────────────────────────────────────────────────────────────────────────
# 6. Evaluate
# ──────────────────────────────────────────────────────────────────────────────
train_score = model_pipeline.score(X_train, y_train)
test_score = model_pipeline.score(X_test, y_test)

y_pred = model_pipeline.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"\n{'─' * 50}")
print(f"  MODEL PERFORMANCE")
print(f"{'─' * 50}")
print(f"  Train R²  : {train_score:.4f}")
print(f"  Test  R²  : {test_score:.4f}")
print(f"  MAE       : {mae:.2f} tCO2e")
print(f"  RMSE      : {rmse:.2f} tCO2e")

# Cross-validation
print(f"\n  5-Fold Cross Validation...")
cv_scores = cross_val_score(model_pipeline, X, y, cv=5, scoring='r2', n_jobs=-1)
print(f"  CV R² scores : {[f'{s:.4f}' for s in cv_scores]}")
print(f"  CV R² mean   : {cv_scores.mean():.4f} (±{cv_scores.std():.4f})")

# Feature importance (from the Random Forest inside the pipeline)
rf_model = model_pipeline.named_steps['regressor']
ohe = model_pipeline.named_steps['preprocessor'].named_transformers_['cat']
cat_feature_names = ohe.get_feature_names_out(categorical_features).tolist()
all_feature_names = cat_feature_names + numerical_features

importances = rf_model.feature_importances_
top_n = 10
sorted_idx = np.argsort(importances)[-top_n:][::-1]

print(f"\n  Top {top_n} Feature Importances:")
for i, idx in enumerate(sorted_idx):
    print(f"    {i+1}. {all_feature_names[idx]:35s} → {importances[idx]:.4f}")

# ──────────────────────────────────────────────────────────────────────────────
# 7. Save the trained model
# ──────────────────────────────────────────────────────────────────────────────
model_path = os.path.join(MODEL_DIR, 'c0_estimator.pkl')
joblib.dump(model_pipeline, model_path)
print(f"\n💾 Saved model: {model_path}")

# ──────────────────────────────────────────────────────────────────────────────
# 8. Sanity-Check Predictions
# ──────────────────────────────────────────────────────────────────────────────
print(f"\n{'─' * 50}")
print(f"  SANITY CHECK PREDICTIONS")
print(f"{'─' * 50}")

test_cases = [
    {'land_size_hectares': 100, 'activity_type': 'Afforestation',
     'climate_zone': 'Tropical Wet', 'state': 'Kerala',
     'project_age_years': 5, 'avg_rainfall_mm': 3000,
     'forest_cover_pct': 52.3, 'soil_organic_carbon': 'High'},
    
    {'land_size_hectares': 50, 'activity_type': 'Reforestation',
     'climate_zone': 'Subtropical', 'state': 'Uttarakhand',
     'project_age_years': 8, 'avg_rainfall_mm': 1800,
     'forest_cover_pct': 45.4, 'soil_organic_carbon': 'High'},
    
    {'land_size_hectares': 200, 'activity_type': 'Regenerative Agriculture',
     'climate_zone': 'Humid Subtropical', 'state': 'Punjab',
     'project_age_years': 3, 'avg_rainfall_mm': 700,
     'forest_cover_pct': 3.6, 'soil_organic_carbon': 'Medium'},
    
    {'land_size_hectares': 150, 'activity_type': 'Afforestation',
     'climate_zone': 'Arid', 'state': 'Rajasthan',
     'project_age_years': 6, 'avg_rainfall_mm': 500,
     'forest_cover_pct': 4.8, 'soil_organic_carbon': 'Very Low'},
    
    {'land_size_hectares': 80, 'activity_type': 'Reforestation',
     'climate_zone': 'Tropical Wet', 'state': 'Meghalaya',
     'project_age_years': 10, 'avg_rainfall_mm': 2800,
     'forest_cover_pct': 76.3, 'soil_organic_carbon': 'High'},
]

test_df = pd.DataFrame(test_cases)
predictions = model_pipeline.predict(test_df)

for i, case in enumerate(test_cases):
    print(f"  {case['state']:20s} | {case['activity_type']:28s} | "
          f"{case['land_size_hectares']:>5} ha | {case['project_age_years']}yr → "
          f"{predictions[i]:>10.2f} tCO2e")

print(f"\n✅ Training complete! Model artifact ready at '{model_path}'")
print("   Your friend can now push this file to the repository.")
