# Generated by Django 5.2.14 on 2026-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c0user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer / Land Owner'), ('buyer', 'Carbon Credit Buyer'), ('admin', 'Platform Admin')], default='farmer', max_length=20),
        ),
    ]
