# Generated by Django 5.2.14 on 2026-05-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_c0user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c0user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer / Land Owner'), ('buyer', 'Carbon Credit Buyer')], default='farmer', max_length=20),
        ),
    ]
