# Generated by Django 5.2.14 on 2026-05-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_c0user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='c0user',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='c0user',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='c0user',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
